Adding time zones to zulu converter
Gabrieldowen/NOTAMyWatch pull request #26
Opened 2024-02-18 21:03 UTC by emilyridge

I condensed the time conversion functions into one function called timeConverter() for less duplicate code. To call you pass in the time and the desired time zone as strings.

2024-02-19 01:48 UTC, n-grounds commented on ZuluConverter.py
> +    zulu_tz = timezone('UTC')                   # Coordinated Universal Time (Zulu)
shouldn't we only initialize these variables if needed in the `if` / `elif` blocks below?  only one of them will ever be needed, right?

2024-02-19 17:00 UTC, JmzCS50 commented on ZuluConverter.py
> +    # Format Zulu time
One way to optimize this to remove the "elif" statements is to use a dictionary to map the time zones to their corresponding timezone objects. Could look like this: 
`from datetime import datetime
timezones = {
    "CST": cst_tz,
    "EST": est_tz,
    "PST": pst_tz,
    "MST": mst_tz,
    "HST": hst_tz,
    "AKST": akst_tz
}

def convert_to_zulu(myDateTime, date_format, zone):
    dateTimeFormatted = datetime.strptime(myDateTime, date_format)
    
    tz = timezones.get(zone)
    if tz is None:
        print("Error: no desired time zone entered")
        return None

    # Localize input for converted datetime
    zoneMatch = tz.localize(dateTimeFormatted)

    # Convert the localized datetime to Zulu time
    zulu_datetime = zoneMatch.astimezone(zulu_tz)
    # Format Zulu time
    zulu_datetime_formatted = zulu_datetime.strftime("%Y-%m-%dT%H:%M:%S.%fZ")

    return zulu_datetime_formatted
`

2024-02-19 17:05 UTC, JmzCS50 commented on ZuluConverter.py
> +    # Format Zulu time
`def convert_to_zulu(myDateTime, date_format, zone):
    dateTimeFormatted = datetime.strptime(myDateTime, date_format)
    
    tz = timezones.get(zone)
    if tz is None:
        print("Error: no desired time zone entered")
        return None

    # Localize input for converted datetime
    zoneMatch = tz.localize(dateTimeFormatted)

    # Convert the localized datetime to Zulu time
    zulu_datetime = zoneMatch.astimezone(zulu_tz)
    # Format Zulu time
    zulu_datetime_formatted = zulu_datetime.strftime("%Y-%m-%dT%H:%M:%S.%fZ")

    return zulu_datetime_formatted`

2024-02-19 17:12 UTC, JmzCS50 requested changes

2024-02-19 17:12 UTC, JmzCS50 commented on ZuluConverter.py
> +    # Format Zulu time
It simplifies the process of selecting the correct timezone by using a dictionary lookup instead of multiple conditional statements.

2024-02-20 20:19 UTC, JmzCS50 approved these changes

2024-02-22 17:00 UTC, Gabrieldowen reviewed
Once the two mentioned changes are made its got my approval!

2024-02-23 02:25 UTC, merged